// Internal, staff-only Business Intake Question Map. Produced by the
// usefulness/completeness/due-diligence audit -- every question retained
// in the public business intake is documented here with its purpose,
// IRS relevance, and downstream effects, so a future editor (human or AI)
// never has to re-derive "why does this question exist" from the SQL
// functions and Section*.tsx files by hand. Never imported into any
// client-facing component.

export type PurposeCategory =
  | "RETURN_PREPARATION"
  | "DEDUCTION_OR_CREDIT"
  | "OWNERSHIP_K1"
  | "BALANCE_SHEET_CAPITAL"
  | "PAYROLL_CONTRACTOR"
  | "ENTITY_CLASSIFICATION"
  | "STATE_SCREENING"
  | "FOREIGN_SCREENING"
  | "COMPLIANCE"
  | "DOCUMENT_REQUEST"
  | "BOOKKEEPING_READINESS"
  | "QUOTE_COMPLEXITY"
  | "STAFF_REVIEW"
  | "CLIENT_IDENTITY";

export interface BusinessIntakeQuestionMapEntry {
  answerKey: string;
  section: number; // 0 = entity routing (public start page, before Section 1)
  sectionTitle: string;
  clientLabel: string;
  purposeCategory: PurposeCategory;
  entityTypesAffected: string;
  businessReason: string;
  irsReference: string;
  conditionalTrigger?: string;
  followUpQuestions?: string;
  staffFlag?: string;
  documentRequest?: string;
  complexityImpact?: string;
  requirement: "required" | "conditional" | "optional" | "staff_only";
  clientCanAnswer: boolean;
  staffFollowUpMayBeRequired: boolean;
}

export const BUSINESS_INTAKE_QUESTION_MAP: BusinessIntakeQuestionMapEntry[] = [
  // ===================================================================
  // Entity routing (public start page, before Section 1)
  // ===================================================================
  {
    answerKey: "entity_classification",
    section: 0,
    sectionTitle: "Entity Routing",
    clientLabel: "How is the business currently taxed for federal purposes? (11 plain-language options)",
    purposeCategory: "ENTITY_CLASSIFICATION",
    entityTypesAffected: "All",
    businessReason:
      "Determines which return (1120/1120-S/1065) applies, which questions and document checklist apply, and routes sole proprietorships and non-electing single-member LLCs to the Individual Tax Intake instead so nothing is asked twice.",
    irsReference: "Determines the applicable return form (1120, 1120-S, or 1065) and whether Schedule C applies instead.",
    followUpQuestions: "elections.form_2553_filed / elections.form_8832_filed for entities that elected corporate taxation.",
    staffFlag: "entity_classification_unclear when 'unsure'.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "legal_business_name",
    section: 0,
    sectionTitle: "Entity Routing",
    clientLabel: "Legal business name",
    purposeCategory: "CLIENT_IDENTITY",
    entityTypesAffected: "All",
    businessReason: "Minimum identity info to open a business client record; used for client/contact matching.",
    irsReference: "Return header (entity name line).",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },

  // ===================================================================
  // Section 1 -- Business Identity & Tax Classification
  // ===================================================================
  {
    answerKey: "entity.dba_name",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Doing-business-as (DBA) name, if any",
    purposeCategory: "CLIENT_IDENTITY",
    entityTypesAffected: "All",
    businessReason: "Used for client matching and correspondence when the business operates under a trade name.",
    irsReference: "Not a return line item; internal identity/matching use only.",
    requirement: "optional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "entity.formation_state / entity.date_formed",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "State of formation / date the business was formed",
    purposeCategory: "RETURN_PREPARATION",
    entityTypesAffected: "All",
    businessReason:
      "Confirms state-filing requirements and entity age. Replaces a prior 'Year Formed' number field that could silently default to 1900 -- this is a proper date input that begins and stays blank until the client enters a real date, and rejects future dates.",
    irsReference: "1120/1120-S: 'Date incorporated'. 1065: 'Date business started'.",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "entity.operations_began_date",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Date the business began operating (if different from the formation date)",
    purposeCategory: "RETURN_PREPARATION",
    entityTypesAffected: "All",
    businessReason: "Formation date and operations-start date can differ (e.g. an entity formed before it began business); relevant to start-up cost treatment and initial-year determination.",
    irsReference: "Relevant to IRC Sec. 195 start-up expenditure treatment and initial-return determination.",
    requirement: "optional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "business EIN (intake_identity_vault, person_type='business')",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Business EIN",
    purposeCategory: "CLIENT_IDENTITY",
    entityTypesAffected: "All",
    businessReason:
      "Required to prepare the return. Stored encrypted in intake_identity_vault, never in the answers JSON; only the last four digits are ever displayed, to staff with permission only.",
    irsReference: "Return header (EIN line), all payroll/information returns.",
    documentRequest: "ein_confirmation_letter",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "entity.tax_year_type / fiscal_year_end_month / fiscal_year_end_day",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "What accounting year does the business use for its federal tax return?",
    purposeCategory: "RETURN_PREPARATION",
    entityTypesAffected: "All",
    businessReason: "A fiscal-year entity has a different due date and requires different period tracking than a calendar-year entity.",
    irsReference: "Return header (tax year begin/end dates).",
    followUpQuestions: "Month/day of fiscal year-end, shown only when 'fiscal' is selected.",
    staffFlag: "fiscal_year_entity",
    complexityImpact: "Fiscal-year entities are treated as Complex.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "entity.business_name_changed / entity.address_changed / entity.accounting_period_changed",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Has the business's legal name/address changed? Did it change its accounting period this year?",
    purposeCategory: "COMPLIANCE",
    entityTypesAffected: "All",
    businessReason: "Name/address changes must be reflected on the return; an accounting-period change generally requires IRS approval (Form 1128) unless an exception applies.",
    irsReference: "Return header name/address-change checkboxes; Form 1128 screening.",
    staffFlag: "entity_profile_change; accounting_period_changed also feeds form_8832_review.",
    requirement: "optional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "address.principal.* (street, unit, city, state, zip, country, foreign_province, foreign_postal_code)",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Principal business address (structured fields, with guidance not to use a registered-agent address)",
    purposeCategory: "RETURN_PREPARATION",
    entityTypesAffected: "All",
    businessReason: "Required on the return header; structured fields (replacing a single free-text field) prevent unusable, unparseable address data and support foreign addresses correctly.",
    irsReference: "Return header (address lines).",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "address.mailing_same_as_principal / address.mailing.*",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Is the mailing address the same as the principal business address?",
    purposeCategory: "RETURN_PREPARATION",
    entityTypesAffected: "All",
    businessReason: "Mailing address can differ from the principal place of business (e.g. a PO box or accountant's office) and IRS correspondence needs to reach the right place.",
    irsReference: "Return header (mailing address, if different).",
    conditionalTrigger: "Structured mailing-address fields only shown when the answer is No.",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "elections.form_2553_filed / acceptance_letter_available",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Was Form 2553 (S-election) filed? Do you have the acceptance letter?",
    purposeCategory: "ENTITY_CLASSIFICATION",
    entityTypesAffected: "S corp, single/multi-member LLC taxed as S corp",
    businessReason: "Confirms the S-election is valid and on file before an 1120-S is prepared.",
    irsReference: "Form 2553; validity of the S-election underlying Form 1120-S.",
    conditionalTrigger: "Shown only when the entity is S-corp-taxed.",
    staffFlag: "s_election_review",
    documentRequest: "form_2553 / s_election_acceptance_letter",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "elections.form_8832_filed / acceptance_letter_available_8832",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Was Form 8832 (entity classification election) filed? Do you have the approval letter?",
    purposeCategory: "ENTITY_CLASSIFICATION",
    entityTypesAffected: "LLC taxed as C corp",
    businessReason: "Confirms the LLC's corporate-tax election is on file before an 1120 is prepared for an entity that would otherwise default to partnership/disregarded treatment.",
    irsReference: "Form 8832; validity of the entity classification election.",
    conditionalTrigger: "Shown only for LLCs taxed as C corp.",
    staffFlag: "form_8832_review",
    documentRequest: "form_8832 / classification_approval_letter",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "filing_history.prior_return_filed / prior_copy_available",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Did the business file a return last year? Do you have a copy?",
    purposeCategory: "RETURN_PREPARATION",
    entityTypesAffected: "All",
    businessReason: "Prior-year figures carry forward (depreciation, basis, carryovers, NOLs).",
    irsReference: "Prior-year return carryforward items (depreciation schedules, loss carryforwards, basis).",
    staffFlag: "missing_prior_return",
    documentRequest: "prior_year_business_return",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "filing_history.unfiled_years",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Are there any prior years that still need to be filed?",
    purposeCategory: "COMPLIANCE",
    entityTypesAffected: "All",
    businessReason: "Unfiled years are a compliance priority that generally must be addressed before the current year can be finalized.",
    irsReference: "Filing-compliance status; potential late-filing penalty exposure.",
    staffFlag: "unfiled_years",
    complexityImpact: "Special Review; consultation recommended.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "filing_history.irs_state_notice",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Has the business received any notice from the IRS or a state tax agency?",
    purposeCategory: "COMPLIANCE",
    entityTypesAffected: "All",
    businessReason: "Notices often carry deadlines; this is the single source of truth for this fact -- deliberately not re-asked in the Compliance section to avoid asking the same fact twice.",
    irsReference: "Open IRS/state correspondence, notices, or proposed assessments.",
    staffFlag: "irs_state_notice",
    documentRequest: "irs_state_notices",
    complexityImpact: "Special Review; consultation recommended.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "filing_history.extension_filed",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Was an extension filed for the tax year covered by this intake?",
    purposeCategory: "COMPLIANCE",
    entityTypesAffected: "All",
    businessReason: "Confirms the correct due date for this return; deliberately year-neutral wording so it needs no annual maintenance.",
    irsReference: "Form 7004 (automatic extension).",
    documentRequest: "extension_confirmation",
    requirement: "optional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "return_status.already_filed / needs_amendment",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Has a federal business return already been filed for this tax year? Does it need to be corrected?",
    purposeCategory: "RETURN_PREPARATION",
    entityTypesAffected: "All",
    businessReason: "Distinguishes an original return in progress from an amendment, a genuinely separate fact from filing_history (which covers last year, not this year).",
    irsReference: "Determines original vs. Form 1120-X / amended Form 1065 or 1120-S treatment.",
    followUpQuestions: "needs_amendment only asked when already_filed = yes.",
    staffFlag: "amended_return; return_status_unclear when 'unsure'.",
    documentRequest: "irs_transcript_request (when amendment needed but no original copy available)",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "return_status.is_initial",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Is this the business's first federal tax return?",
    purposeCategory: "RETURN_PREPARATION",
    entityTypesAffected: "All",
    businessReason: "Initial returns have different start-up-cost and depreciation-convention treatment and check a different box on the return.",
    irsReference: "Return header 'Initial return' checkbox.",
    staffFlag: "initial_return",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "return_status.is_final",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Is this expected to be the business's final federal tax return?",
    purposeCategory: "RETURN_PREPARATION",
    entityTypesAffected: "All",
    businessReason: "Final returns require liquidation/dissolution reporting and different Schedule K-1 treatment for owners.",
    irsReference: "Return header 'Final return' checkbox; liquidating distribution reporting.",
    staffFlag: "final_return",
    complexityImpact: "Special Review; consultation recommended.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "return_status.is_short_period / short_period_begin / short_period_end / short_period_reason",
    section: 1,
    sectionTitle: "Business Identity & Tax Classification",
    clientLabel: "Does this return cover fewer than 12 months? (with begin/end dates and reason)",
    purposeCategory: "RETURN_PREPARATION",
    entityTypesAffected: "All",
    businessReason: "A short tax year changes proration of certain limits and deductions; the reason (accounting-period change vs. other) is only asked when not already explained by the initial/final answers, avoiding a duplicate question.",
    irsReference: "Short-period return rules (proration of Sec. 179, standard deduction-equivalent limits, etc.).",
    staffFlag: "short_period_return",
    complexityImpact: "Complex.",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },

  // ===================================================================
  // Section 2 -- Owners, Shareholders & Partners
  // ===================================================================
  {
    answerKey: "owners[] (full_name, role, ownership_pct, ownership_unsure)",
    section: 2,
    sectionTitle: "Owners, Shareholders & Partners",
    clientLabel: "Owner name, role, and ownership percentage",
    purposeCategory: "OWNERSHIP_K1",
    entityTypesAffected: "All (except sole proprietorships, which never reach this intake)",
    businessReason: "Required for K-1/1120-S/1065 allocations; repeatable so any number of owners can be added.",
    irsReference: "Schedule K-1 (all three return types); Schedule B-1 (1120-S) / B-2 (1065) ownership disclosure thresholds.",
    staffFlag: "ownership_percentage_review when percentages don't sum to ~100%.",
    documentRequest: "ownership_ledger",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "owners[].ownership_changed_during_year / ownership_pct_beginning / ownership_change_effective_date",
    section: 2,
    sectionTitle: "Owners, Shareholders & Partners",
    clientLabel: "Did this owner's percentage change during the year? Beginning percentage and effective date.",
    purposeCategory: "OWNERSHIP_K1",
    entityTypesAffected: "All",
    businessReason: "Mid-year ownership changes require allocating income/loss across the change (varying-interest rules for partnerships; per-share-per-day for S corps).",
    irsReference: "Schedule K-1 beginning/ending ownership percentage; IRC Sec. 706(d) (partnerships) / Sec. 1377 (S corps) varying-interest allocation.",
    conditionalTrigger: "Beginning percentage and date only shown when the change flag is Yes.",
    staffFlag: "ownership_change_missing_effective_date when the change is flagged but no date is entered.",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "owner tax ID (intake_identity_vault, person_type='owner')",
    section: 2,
    sectionTitle: "Owners, Shareholders & Partners",
    clientLabel: "Owner SSN/ITIN/EIN",
    purposeCategory: "CLIENT_IDENTITY",
    entityTypesAffected: "All",
    businessReason: "Required for K-1 preparation. Stored encrypted, keyed to the owner's stable local_id so it survives reordering; masked-only display.",
    irsReference: "Schedule K-1 (owner's identifying number).",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "owners[].received_compensation / received_distributions",
    section: 2,
    sectionTitle: "Owners, Shareholders & Partners",
    clientLabel: "Did this owner receive compensation (W-2 wages) or distributions?",
    purposeCategory: "OWNERSHIP_K1",
    entityTypesAffected: "All",
    businessReason: "Plain-fact question ('did they receive W-2 wages') that lets the preparer make the reasonable-compensation determination -- the client is never asked to judge reasonableness directly.",
    irsReference: "Form 1125-E (officer compensation); Schedule K-1 distributions; S-corp reasonable-compensation doctrine (Rev. Rul. 74-44 and successors).",
    staffFlag: "owner_compensation_review; combined with S-corp status drives s_corp_distributions_no_wages reasonable-inquiry.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "owners[].had_loans",
    section: 2,
    sectionTitle: "Owners, Shareholders & Partners",
    clientLabel: "Did this owner make or receive any loans to/from the business?",
    purposeCategory: "BALANCE_SHEET_CAPITAL",
    entityTypesAffected: "All",
    businessReason: "Related-party loans require disclosure, an interest-rate/AFR check, and possible reclassification as a distribution or capital contribution.",
    irsReference: "Schedule L (balance sheet, loans to/from shareholders/partners); related-party interest rules (IRC Sec. 267).",
    staffFlag: "related_party_transactions; shareholder_loan_no_records reasonable-inquiry when basis records are also missing.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "owners[].is_foreign",
    section: 2,
    sectionTitle: "Owners, Shareholders & Partners",
    clientLabel: "Is this owner a foreign person (not a U.S. citizen or resident)?",
    purposeCategory: "FOREIGN_SCREENING",
    entityTypesAffected: "All",
    businessReason: "A nonresident alien is not an eligible S-corp shareholder, and foreign partners/shareholders trigger withholding and information-reporting requirements.",
    irsReference: "IRC Sec. 1361(b)(1)(C) S-corp eligible shareholder rules; Form 1042/8804 withholding screening; K-2/K-3 screening.",
    staffFlag: "foreign_ownership_review; foreign_owner_s_corp_eligibility_review reasonable-inquiry for S-corp-taxed entities.",
    complexityImpact: "Special Review.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "owners[].received_guaranteed_payments",
    section: 2,
    sectionTitle: "Owners, Shareholders & Partners",
    clientLabel: "Did this owner receive guaranteed payments from the business?",
    purposeCategory: "OWNERSHIP_K1",
    entityTypesAffected: "Partnership, multi-member LLC taxed as partnership",
    businessReason: "Guaranteed payments are reported separately from ordinary income allocation and affect self-employment tax.",
    irsReference: "Schedule K-1, Box 4 (guaranteed payments); IRC Sec. 707(c).",
    conditionalTrigger: "Shown only for partnership-taxed entities.",
    staffFlag: "guaranteed_payments_review; guaranteed_payments_capital_review reasonable-inquiry when capital records are also missing.",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "owners[].shareholder_health_insurance",
    section: 2,
    sectionTitle: "Owners, Shareholders & Partners",
    clientLabel: "Did the business pay for this owner's health insurance?",
    purposeCategory: "PAYROLL_CONTRACTOR",
    entityTypesAffected: "S corp, single/multi-member LLC taxed as S corp",
    businessReason: "S-corp shareholder health insurance has a specific W-2 Box 1/14 reporting requirement to be deductible and to flow through correctly to the shareholder's individual return.",
    irsReference: "Notice 2008-1; W-2 Box 1 and 14 treatment for >2% S-corp shareholders.",
    conditionalTrigger: "Shown only for S-corp-taxed entities.",
    staffFlag: "shareholder_health_insurance_review (staff-only reasonable inquiry -- payroll treatment is a preparer judgment call).",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "ownership_structure.basis_records",
    section: 2,
    sectionTitle: "Owners, Shareholders & Partners",
    clientLabel: "Do you have records showing each owner's investment and activity in the business?",
    purposeCategory: "OWNERSHIP_K1",
    entityTypesAffected: "All",
    businessReason: "Plain-language basis question -- clients are never asked to self-assess 'basis' directly; this single answer feeds every basis-dependent reasonable-inquiry rule (loans, guaranteed payments, dividends).",
    irsReference: "Form 7203 (S-corp shareholder basis); partner capital-account rules (Schedule K-1, Item L); C-corp shareholder basis for distribution characterization.",
    staffFlag: "basis_records_review",
    documentRequest: "basis_worksheets",
    complexityImpact: "Complex.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },

  // ===================================================================
  // Section 3 -- Business Operations & Locations
  // ===================================================================
  {
    answerKey: "operations.business_description",
    section: 3,
    sectionTitle: "Business Operations & Locations",
    clientLabel: "Briefly describe what the business does",
    purposeCategory: "RETURN_PREPARATION",
    entityTypesAffected: "All",
    businessReason: "Determines the business activity code on the return and informs the preparer's read of unusual transactions.",
    irsReference: "Return header business activity code / principal business activity.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey:
      "state_activity.{offices_other_states,employees_other_states,property_inventory_other_states,registered_other_states,prior_state_returns,services_performed_other_states,marketplace_online_sales,payroll_other_states,sales_tax_registrations,unsure}",
    section: 3,
    sectionTitle: "Business Operations & Locations",
    clientLabel: "Facts about activity outside the business's home state (nine plain yes/no questions the client can actually answer, never 'is there nexus?')",
    purposeCategory: "STATE_SCREENING",
    entityTypesAffected: "All",
    businessReason: "Collects the underlying facts a preparer needs to determine state filing requirements without asking the client to make a nexus determination themselves.",
    irsReference: "Not federal; drives state-return screening and multistate apportionment review.",
    staffFlag: "multistate_return_review / state_filing_review; sales_by_state_report_needed when marketplace sales exist without a report.",
    complexityImpact: "Complex.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "states_lived_worked (reused from the shared intake column)",
    section: 3,
    sectionTitle: "Business Operations & Locations",
    clientLabel: "Which state(s)? (only shown once any out-of-state activity fact above is Yes)",
    purposeCategory: "STATE_SCREENING",
    entityTypesAffected: "All",
    businessReason: "Reuses the same states_lived_worked column the individual intake uses rather than a duplicate states_operated column; only asked once a reason to ask it exists.",
    irsReference: "Identifies which state returns to screen for.",
    conditionalTrigger: "Shown only when at least one state_activity fact is Yes.",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "foreign_activity.has_foreign_activity / categories.*",
    section: 3,
    sectionTitle: "Business Operations & Locations",
    clientLabel: "Does the business have foreign owners, accounts, income, property, or transactions? (with category checkboxes)",
    purposeCategory: "FOREIGN_SCREENING",
    entityTypesAffected: "All",
    businessReason: "Screens for international-reporting triggers without asking the client to name required forms themselves.",
    irsReference: "K-2/K-3 screening; FBAR/Form 8938 screening; Form 5471/8865/926 screening depending on category.",
    followUpQuestions: "Category checkboxes shown only when the top-level answer is Yes.",
    staffFlag: "foreign_reporting_review; foreign_activity_category_unclear if Yes but no category selected.",
    complexityImpact: "Special Review.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },

  // ===================================================================
  // Section 4 -- Financial Records, Income & Expenses
  // ===================================================================
  {
    answerKey: "bookkeeping.status",
    section: 4,
    sectionTitle: "Financial Records, Income & Expenses",
    clientLabel: "How would you describe the business's bookkeeping for this year?",
    purposeCategory: "BOOKKEEPING_READINESS",
    entityTypesAffected: "All",
    businessReason: "Incomplete bookkeeping drives a cleanup recommendation and consultation before the return can proceed.",
    irsReference: "Not a return line; preparation-readiness screening.",
    staffFlag: "bookkeeping_cleanup_recommended",
    complexityImpact: "Complex when incomplete/none/mostly/unsure.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "bookkeeping.bank_reconciled",
    section: 4,
    sectionTitle: "Financial Records, Income & Expenses",
    clientLabel: "Are the business bank accounts reconciled through year-end?",
    purposeCategory: "BOOKKEEPING_READINESS",
    entityTypesAffected: "All",
    businessReason: "Unreconciled accounts are a strong signal the P&L/balance sheet can't be relied on as-is.",
    irsReference: "Preparation-readiness screening.",
    staffFlag: "bookkeeping_cleanup_recommended",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey:
      "financial_records.{pl_statement,balance_sheet,bank_statements,trial_balance,general_ledger,credit_card_statements,loan_statements,fixed_asset_schedule}",
    section: 4,
    sectionTitle: "Financial Records, Income & Expenses",
    clientLabel: "Which financial records do you have available? (availability only, not amounts)",
    purposeCategory: "DOCUMENT_REQUEST",
    entityTypesAffected: "All",
    businessReason: "Each answer gates exactly one matching document request -- the client is never asked to retype amounts a P&L or ledger will supply.",
    irsReference: "Schedule L (balance sheet); underlying support for every income and expense line.",
    documentRequest: "pl_statement / balance_sheet / trial_balance / general_ledger / bank_statements / credit_card_statements / loan_statements / fixed_asset_schedule",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "inventory.carries_inventory / method / records_available / physical_count_done / has_obsolete_damaged",
    section: 4,
    sectionTitle: "Financial Records, Income & Expenses",
    clientLabel: "Does the business carry inventory? Valuation method, records, physical count, obsolete/damaged items.",
    purposeCategory: "RETURN_PREPARATION",
    entityTypesAffected: "All",
    businessReason: "Cost of goods sold cannot be computed without beginning/ending inventory and a valuation method; this was a gap in the prior round (inventory availability was only a generic checkbox with no COGS-specific screening).",
    irsReference: "Form 1125-A (cost of goods sold).",
    conditionalTrigger: "Follow-ups shown only when carries_inventory is Yes.",
    staffFlag: "inventory_cogs_screening / inventory_review; inventory_no_records reasonable-inquiry when records are unavailable.",
    documentRequest: "inventory_report",
    complexityImpact: "Complex.",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey:
      "income_sources.{rental_real_estate,portfolio_investment,marketplace_platform_income,cash_income,debt_cancellation,grants_received,insurance_proceeds}",
    section: 4,
    sectionTitle: "Financial Records, Income & Expenses",
    clientLabel: "Did the business have any of: rental income, investment income, marketplace/payment-platform income, cash income, cancelled debt, grants, or insurance proceeds?",
    purposeCategory: "RETURN_PREPARATION",
    entityTypesAffected: "All",
    businessReason: "Screens for income types that a plain P&L review might miss or that need special schedule treatment; a prior round had no income screening at all beyond bookkeeping-record availability.",
    irsReference: "Form 8825 (rental real estate, for partnerships/S corps); Schedule B-equivalent interest/dividend detail; 1099-K reconciliation; IRC Sec. 108 cancellation-of-debt income.",
    staffFlag: "rental_real_estate_screening / portfolio_income_screening / marketplace_income_reconciliation / unrecorded_income_review / cancellation_of_debt_income",
    complexityImpact: "cash_income and debt_cancellation drive consultation/Special Review.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey:
      "deductions_screening.{retirement_plan_contributions,employee_benefit_programs,owner_paid_business_expenses,business_expenses_paid_personally,home_office_or_owner_reimbursement}",
    section: 4,
    sectionTitle: "Financial Records, Income & Expenses",
    clientLabel: "Retirement contributions, employee benefits, owner-paid expenses, business funds used personally, home-office use?",
    purposeCategory: "DEDUCTION_OR_CREDIT",
    entityTypesAffected: "All",
    businessReason: "These specific deduction categories often aren't cleanly captured on a P&L (retirement plan elections, accountable-plan reimbursements, commingled personal/business expenses) and need separate preparer handling even when full bookkeeping records exist.",
    irsReference: "Retirement plan deduction limits; accountable-plan reimbursement rules; home-office deduction (partnership/S-corp unreimbursed-expense treatment differs by entity type).",
    staffFlag: "owner_expense_reimbursement_review / home_office_reimbursement_review",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },

  // ===================================================================
  // Section 5 -- Payroll, Contractors & Owner Compensation
  // ===================================================================
  {
    answerKey: "payroll.has_employees / employee_count / provider_name",
    section: 5,
    sectionTitle: "Payroll, Contractors & Owner Compensation",
    clientLabel: "Employee count and payroll provider",
    purposeCategory: "PAYROLL_CONTRACTOR",
    entityTypesAffected: "All",
    businessReason: "Determines whether payroll forms (941/940, W-2/W-3) apply and are requested.",
    irsReference: "Forms 941, 940, W-2, W-3.",
    documentRequest: "payroll_summary / form_941_940 / w2_w3",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "payroll.reports_available / all_returns_filed / late_deposits / unpaid_payroll_tax",
    section: 5,
    sectionTitle: "Payroll, Contractors & Owner Compensation",
    clientLabel: "Payroll compliance questions (reports available, filed on time, deposits, unpaid tax)",
    purposeCategory: "PAYROLL_CONTRACTOR",
    entityTypesAffected: "All",
    businessReason: "Payroll tax problems are high-priority compliance issues distinct from ordinary return preparation.",
    irsReference: "Payroll tax compliance (Trust Fund Recovery Penalty exposure for unpaid amounts).",
    staffFlag: "payroll_compliance_review / late_payroll_filing / unpaid_payroll_tax; employees_no_payroll_reports reasonable-inquiry when reports aren't available.",
    complexityImpact: "unpaid_payroll_tax drives Special Review.",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "contractors.has_contractors / contractor_count / w9_collected / forms_1099_filed",
    section: 5,
    sectionTitle: "Payroll, Contractors & Owner Compensation",
    clientLabel: "Contractor count, W-9s on file, and whether 1099s have been filed",
    purposeCategory: "PAYROLL_CONTRACTOR",
    entityTypesAffected: "All",
    businessReason: "Determines 1099 filing requirements and status.",
    irsReference: "Forms 1099-NEC / 1099-MISC.",
    documentRequest: "form_1099_nec / w9_records",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "contractors.unreported_payments / worker_classification_concern",
    section: 5,
    sectionTitle: "Payroll, Contractors & Owner Compensation",
    clientLabel: "Any contractor payments that may be unreported, or workers who may be misclassified?",
    purposeCategory: "COMPLIANCE",
    entityTypesAffected: "All",
    businessReason: "Worker misclassification is an IRS audit trigger requiring careful review, not a client-side legal determination.",
    irsReference: "Worker classification (common-law employee vs. independent contractor); Form SS-8 screening.",
    staffFlag: "contractor_reporting_review",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "(derived) s_corp_reasonable_compensation_review",
    section: 5,
    sectionTitle: "Payroll, Contractors & Owner Compensation",
    clientLabel: "(No question asked -- automatic; a disclaimer note explains this to the client)",
    purposeCategory: "STAFF_REVIEW",
    entityTypesAffected: "S corp, single/multi-member LLC taxed as S corp",
    businessReason: "Automatically flagged whenever the entity is S-corp-taxed, since reasonable-compensation analysis is a preparer judgment call, not something clients should be asked to interpret ('is compensation reasonable?' is explicitly the wrong question to ask a client).",
    irsReference: "S-corp reasonable-compensation doctrine.",
    staffFlag: "s_corp_reasonable_compensation_review",
    requirement: "staff_only",
    clientCanAnswer: false,
    staffFollowUpMayBeRequired: true,
  },

  // ===================================================================
  // Section 6 -- Assets, Vehicles, Inventory & Loans
  // ===================================================================
  {
    answerKey: "assets.purchased_real_property",
    section: 6,
    sectionTitle: "Assets, Vehicles, Inventory & Loans",
    clientLabel: "Did the business purchase real property or major equipment this year?",
    purposeCategory: "DEDUCTION_OR_CREDIT",
    entityTypesAffected: "All",
    businessReason: "Drives fixed-asset and depreciation setup for new purchases.",
    irsReference: "Form 4562 (depreciation and Sec. 179/bonus depreciation screening).",
    documentRequest: "closing_statements",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "assets.disposed_assets",
    section: 6,
    sectionTitle: "Assets, Vehicles, Inventory & Loans",
    clientLabel: "Did the business sell or dispose of any assets this year?",
    purposeCategory: "RETURN_PREPARATION",
    entityTypesAffected: "All",
    businessReason:
      "Sole source of truth for asset disposals -- the 'asset_sale' staff-review flag reads this same answer rather than a second, duplicate question in the Compliance section (an inconsistency found and fixed during this audit).",
    irsReference: "Form 4797 (sales of business property); depreciation recapture.",
    staffFlag: "asset_sale; asset_sale_no_fixed_asset_records reasonable-inquiry when no depreciation schedule is available.",
    documentRequest: "closing_statements",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "vehicles.owned_or_leased / personal_used_for_business / mileage_records_available",
    section: 6,
    sectionTitle: "Assets, Vehicles, Inventory & Loans",
    clientLabel: "Business vehicles owned/leased, personal vehicle used for business, and whether mileage is tracked",
    purposeCategory: "DEDUCTION_OR_CREDIT",
    entityTypesAffected: "All",
    businessReason: "Determines whether mileage/vehicle records are requested and whether the business-use percentage claim is supportable.",
    irsReference: "Vehicle expense deduction (standard mileage vs. actual expense); substantiation requirements (IRC Sec. 274(d)).",
    staffFlag: "vehicle_no_mileage_records reasonable-inquiry when a personal vehicle is used but no mileage records exist.",
    documentRequest: "vehicle_mileage_records",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "loans[] (lender_name, purpose)",
    section: 6,
    sectionTitle: "Assets, Vehicles, Inventory & Loans",
    clientLabel: "Business loans (lender and purpose)",
    purposeCategory: "BALANCE_SHEET_CAPITAL",
    entityTypesAffected: "All",
    businessReason: "Repeatable list of business loans; any entry triggers a loan-documents request for balance confirmation and interest support.",
    irsReference: "Schedule L (liabilities); interest expense support.",
    documentRequest: "loan_documents",
    requirement: "optional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "equity.negative_capital_accounts",
    section: 6,
    sectionTitle: "Assets, Vehicles, Inventory & Loans",
    clientLabel: "Do any owner capital accounts have a negative balance?",
    purposeCategory: "BALANCE_SHEET_CAPITAL",
    entityTypesAffected: "All",
    businessReason: "Negative capital accounts can trigger gain recognition and require preparer review; the client is told it's fine to leave as No if unsure rather than guess.",
    irsReference: "Schedule M-2 (analysis of capital accounts); potential gain recognition on negative basis.",
    staffFlag: "negative_capital_review",
    complexityImpact: "Special Review.",
    requirement: "optional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "c_corp.dividends_paid",
    section: 6,
    sectionTitle: "Assets, Vehicles, Inventory & Loans",
    clientLabel: "Did the business pay any dividends to shareholders this year?",
    purposeCategory: "OWNERSHIP_K1",
    entityTypesAffected: "C corp only",
    businessReason: "Dividends require Form 1099-DIV issuance and E&P tracking, distinct from S-corp/partnership distribution treatment.",
    irsReference: "Form 1099-DIV; earnings and profits (E&P) tracking.",
    conditionalTrigger: "Shown only for true C corporations.",
    staffFlag: "dividends_review; c_corp_dividends_ownership_review reasonable-inquiry when ownership records are also missing.",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },

  // ===================================================================
  // Section 7 -- Changes & Compliance
  // ===================================================================
  {
    answerKey: "business_status.was_sold / was_merged / was_converted / dissolved / ownership_changed",
    section: 7,
    sectionTitle: "Changes & Compliance",
    clientLabel: "Was the business sold, merged, converted, dissolved, or did ownership change this year?",
    purposeCategory: "COMPLIANCE",
    entityTypesAffected: "All",
    businessReason: "Any of these events materially changes how the return is prepared and may require a final or short-period return; cross-checked against the return_status.is_final answer via the reasonable-inquiry workflow.",
    irsReference: "Final-return reporting; liquidation/dissolution rules; entity-conversion tax treatment.",
    staffFlag: "business_sale / merger_or_conversion / dissolution / ownership_change; final_return_no_closure_event reasonable-inquiry when is_final=Yes but none of these are indicated.",
    documentRequest: "closing_statements",
    complexityImpact: "Special Review for sold/merged/converted/dissolved.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "changes_compliance.related_party.{with_owners,with_relatives,with_commonly_owned}",
    section: 7,
    sectionTitle: "Changes & Compliance",
    clientLabel: "Did the business pay rent, fees, wages, or loan payments to, or otherwise buy/sell/lease something with, an owner, a relative, or a commonly-owned business?",
    purposeCategory: "COMPLIANCE",
    entityTypesAffected: "All",
    businessReason:
      "Broader related-party transactions distinct from the per-owner loan question in Section 2 -- captures purchases, sales, leases, rent, fees, and wages paid to related parties, not just loans. Worded as concrete facts per the audit's plain-language requirement instead of asking 'was there a related-party transaction?'",
    irsReference: "IRC Sec. 267 related-party rules; Schedule B-1/B-2 disclosure of related ownership.",
    staffFlag: "related_party_transactions",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "changes_compliance.tax_compliance.audit / lien_or_levy / installment_agreement",
    section: 7,
    sectionTitle: "Changes & Compliance",
    clientLabel: "Is the business under audit? Does it have a tax lien or levy? Is it on a payment plan?",
    purposeCategory: "COMPLIANCE",
    entityTypesAffected: "All",
    businessReason: "High-priority compliance issues requiring immediate staff attention and coordination with any prior representative.",
    irsReference: "Open examination; collection actions; existing installment agreement terms.",
    staffFlag: "audit/lien_or_levy drive Special Review directly.",
    documentRequest: "audit_correspondence / payment_plan_documents",
    complexityImpact: "Special Review.",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "changes_compliance.special_transactions.{lawsuit_settlement,bankruptcy,disaster_loss,fraud_theft_embezzlement}",
    section: 7,
    sectionTitle: "Changes & Compliance",
    clientLabel: "Lawsuit settlement, bankruptcy, casualty/disaster loss, or fraud/theft/embezzlement this year?",
    purposeCategory: "COMPLIANCE",
    entityTypesAffected: "All",
    businessReason: "Each of these has distinct, non-obvious tax treatment (settlement character, discharge-of-debt income in bankruptcy, casualty-loss deduction rules, theft-loss deduction rules) that a client cannot be expected to self-classify.",
    irsReference: "Settlement/lawsuit proceeds character; IRC Sec. 108 bankruptcy exclusion; casualty/theft loss deduction (Sec. 165).",
    staffFlag: "lawsuit_settlement_review / bankruptcy_review / disaster_loss_review / fraud_theft_review",
    documentRequest: "settlement_documents / bankruptcy_documents / disaster_loss_documents",
    complexityImpact: "lawsuit_settlement, bankruptcy, and fraud/theft drive Special Review.",
    requirement: "optional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },

  // ===================================================================
  // Section 8 -- Documents, Review, Verification & Submission
  // ===================================================================
  {
    answerKey: "(document uploads)",
    section: 8,
    sectionTitle: "Documents, Review, Verification & Submission",
    clientLabel: "Upload requested documents",
    purposeCategory: "DOCUMENT_REQUEST",
    entityTypesAffected: "All",
    businessReason: "Reuses the same intake_document_requests/intake_documents tables and upload UI as the individual intake -- no duplicate upload infrastructure.",
    irsReference: "N/A (infrastructure).",
    requirement: "conditional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
  {
    answerKey: "(reasonable-inquiry follow-up responses)",
    section: 8,
    sectionTitle: "Documents, Review, Verification & Submission",
    clientLabel: "A few follow-up questions (only shown when a cross-section conflict was detected)",
    purposeCategory: "STAFF_REVIEW",
    entityTypesAffected: "All",
    businessReason:
      "Surfaces only the reasonable-inquiry categories that have a genuine client-answerable follow-up (e.g. 'you said first return, but also that one was filed last year -- can you clarify?'); staff-only judgment categories (e.g. reasonable compensation) are never shown to the client. Answering is encouraged but does not block submission.",
    irsReference: "Supports a documented reasonable-inquiry record for ambiguous or conflicting answers.",
    requirement: "optional",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: true,
  },
  {
    answerKey: "(verification + submission)",
    section: 8,
    sectionTitle: "Documents, Review, Verification & Submission",
    clientLabel: "Verify email/phone and submit",
    purposeCategory: "CLIENT_IDENTITY",
    entityTypesAffected: "All",
    businessReason: "Reuses verify_intake_code and submit_intake unchanged -- these RPCs are generic across intake types.",
    irsReference: "N/A (infrastructure).",
    requirement: "required",
    clientCanAnswer: true,
    staffFollowUpMayBeRequired: false,
  },
];
