-- Continuation of least_privilege_public_grant_corrective_fix (parts 2 and 3
-- of the same sweep, applied moments later in production) -- same rationale,
-- same hardening-only nature.

revoke execute on function public._maybe_enter_review(p_onboarding_id uuid) from public;
revoke execute on function public._maybe_enter_review(p_onboarding_id uuid) from anon;
revoke execute on function public._maybe_enter_review(p_onboarding_id uuid) from authenticated;
revoke execute on function public._maybe_reach_partner_onboarding_ready(p_onboarding_id uuid) from public;
revoke execute on function public._maybe_reach_partner_onboarding_ready(p_onboarding_id uuid) from anon;
revoke execute on function public._maybe_reach_partner_onboarding_ready(p_onboarding_id uuid) from authenticated;
revoke execute on function public._notify_admins_of_organizer_submitted(p_workspace_id uuid, p_client_id uuid, p_response_id uuid, p_organizer_template_id uuid) from public;
revoke execute on function public._notify_admins_of_organizer_submitted(p_workspace_id uuid, p_client_id uuid, p_response_id uuid, p_organizer_template_id uuid) from anon;
revoke execute on function public._notify_admins_of_organizer_submitted(p_workspace_id uuid, p_client_id uuid, p_response_id uuid, p_organizer_template_id uuid) from authenticated;
revoke execute on function public._notify_admins_of_quote_response(p_workspace_id uuid, p_client_id uuid, p_quote_id uuid, p_response text) from public;
revoke execute on function public._notify_admins_of_quote_response(p_workspace_id uuid, p_client_id uuid, p_quote_id uuid, p_response text) from anon;
revoke execute on function public._notify_admins_of_quote_response(p_workspace_id uuid, p_client_id uuid, p_quote_id uuid, p_response text) from authenticated;
revoke execute on function public._partner_onboarding_agreement_signed() from public;
revoke execute on function public._partner_onboarding_agreement_signed() from anon;
revoke execute on function public._partner_onboarding_agreement_signed() from authenticated;
revoke execute on function public._partner_onboarding_documents_completed() from public;
revoke execute on function public._partner_onboarding_documents_completed() from anon;
revoke execute on function public._partner_onboarding_documents_completed() from authenticated;
revoke execute on function public._propose_client_field_from_organizer_answer(p_workspace_id uuid, p_client_id uuid, p_organizer_response_id uuid, p_organizer_field_id uuid, p_client_profile_field text, p_value jsonb) from public;
revoke execute on function public._propose_client_field_from_organizer_answer(p_workspace_id uuid, p_client_id uuid, p_organizer_response_id uuid, p_organizer_field_id uuid, p_client_profile_field text, p_value jsonb) from anon;
revoke execute on function public._propose_client_field_from_organizer_answer(p_workspace_id uuid, p_client_id uuid, p_organizer_response_id uuid, p_organizer_field_id uuid, p_client_profile_field text, p_value jsonb) from authenticated;
revoke execute on function public._resolve_onboarding_default_reviewer(p_workspace_id uuid, p_firm_connection_id uuid) from public;
revoke execute on function public._resolve_onboarding_default_reviewer(p_workspace_id uuid, p_firm_connection_id uuid) from anon;
revoke execute on function public._resolve_onboarding_default_reviewer(p_workspace_id uuid, p_firm_connection_id uuid) from authenticated;
revoke execute on function public.advance_pipeline_on_stage_completed() from public;
revoke execute on function public.advance_pipeline_on_stage_completed() from anon;
revoke execute on function public.advance_pipeline_on_stage_completed() from authenticated;
revoke execute on function public.append_agent_run_event(p_run_id uuid, p_level text, p_message text, p_meta jsonb) from public;
revoke execute on function public.append_agent_run_event(p_run_id uuid, p_level text, p_message text, p_meta jsonb) from anon;
revoke execute on function public.append_agent_run_event(p_run_id uuid, p_level text, p_message text, p_meta jsonb) from authenticated;
revoke execute on function public.apply_pipeline_stage_default_assignment() from public;
revoke execute on function public.apply_pipeline_stage_default_assignment() from anon;
revoke execute on function public.apply_pipeline_stage_default_assignment() from authenticated;
revoke execute on function public.auto_assign_client_relationship_manager() from public;
revoke execute on function public.auto_assign_client_relationship_manager() from anon;
revoke execute on function public.auto_assign_client_relationship_manager() from authenticated;
revoke execute on function public.cancel_overdue_quotes() from public;
revoke execute on function public.cancel_overdue_quotes() from anon;
revoke execute on function public.cancel_overdue_quotes() from authenticated;
revoke execute on function public.cleanup_pipeline_runs_on_client_delete() from public;
revoke execute on function public.cleanup_pipeline_runs_on_client_delete() from anon;
revoke execute on function public.cleanup_pipeline_runs_on_client_delete() from authenticated;
revoke execute on function public.cleanup_pipeline_runs_on_engagement_delete() from public;
revoke execute on function public.cleanup_pipeline_runs_on_engagement_delete() from anon;
revoke execute on function public.cleanup_pipeline_runs_on_engagement_delete() from authenticated;
revoke execute on function public.complete_agent_run(p_run_id uuid, p_status text, p_summary jsonb, p_ai_analysis jsonb, p_error_message text) from public;
revoke execute on function public.complete_agent_run(p_run_id uuid, p_status text, p_summary jsonb, p_ai_analysis jsonb, p_error_message text) from anon;
revoke execute on function public.complete_agent_run(p_run_id uuid, p_status text, p_summary jsonb, p_ai_analysis jsonb, p_error_message text) from authenticated;
revoke execute on function public.correlate_agent_findings(p_finding_id_a uuid, p_finding_id_b uuid, p_relationship text, p_confidence text) from public;
revoke execute on function public.correlate_agent_findings(p_finding_id_a uuid, p_finding_id_b uuid, p_relationship text, p_confidence text) from anon;
revoke execute on function public.correlate_agent_findings(p_finding_id_a uuid, p_finding_id_b uuid, p_relationship text, p_confidence text) from authenticated;
revoke execute on function public.create_agent_finding(p_agent_key text, p_run_id uuid, p_workspace_id uuid, p_category text, p_severity text, p_title text, p_description text, p_fingerprint text, p_expected_behavior text, p_actual_behavior text, p_reproduction_steps jsonb, p_affected_module text, p_related_record_type text, p_related_record_id text, p_ai_analysis jsonb, p_possible_cause text) from public;
revoke execute on function public.create_agent_finding(p_agent_key text, p_run_id uuid, p_workspace_id uuid, p_category text, p_severity text, p_title text, p_description text, p_fingerprint text, p_expected_behavior text, p_actual_behavior text, p_reproduction_steps jsonb, p_affected_module text, p_related_record_type text, p_related_record_id text, p_ai_analysis jsonb, p_possible_cause text) from anon;
revoke execute on function public.create_agent_finding(p_agent_key text, p_run_id uuid, p_workspace_id uuid, p_category text, p_severity text, p_title text, p_description text, p_fingerprint text, p_expected_behavior text, p_actual_behavior text, p_reproduction_steps jsonb, p_affected_module text, p_related_record_type text, p_related_record_id text, p_ai_analysis jsonb, p_possible_cause text) from authenticated;
revoke execute on function public.create_organizer_information_request(p_response_id uuid, p_message text, p_organizer_field_id uuid, p_send_email boolean, p_send_sms boolean, p_show_in_portal boolean) from public;
revoke execute on function public.create_organizer_information_request(p_response_id uuid, p_message text, p_organizer_field_id uuid, p_send_email boolean, p_send_sms boolean, p_show_in_portal boolean) from anon;
revoke execute on function public.create_organizer_information_request(p_response_id uuid, p_message text, p_organizer_field_id uuid, p_send_email boolean, p_send_sms boolean, p_show_in_portal boolean) from authenticated;
revoke execute on function public.enforce_default_reviewer_is_ero_member() from public;
revoke execute on function public.enforce_default_reviewer_is_ero_member() from anon;
revoke execute on function public.enforce_default_reviewer_is_ero_member() from authenticated;
revoke execute on function public.enforce_ero_staff_assignment_restriction() from public;
revoke execute on function public.enforce_ero_staff_assignment_restriction() from anon;
revoke execute on function public.enforce_ero_staff_assignment_restriction() from authenticated;
revoke execute on function public.enforce_onboarding_stage_source_of_truth() from public;
revoke execute on function public.enforce_onboarding_stage_source_of_truth() from anon;
revoke execute on function public.enforce_onboarding_stage_source_of_truth() from authenticated;
revoke execute on function public.enforce_storage_capacity() from public;
revoke execute on function public.enforce_storage_capacity() from anon;
revoke execute on function public.enforce_storage_capacity() from authenticated;
revoke execute on function public.enqueue_calendar_sync() from public;
revoke execute on function public.enqueue_calendar_sync() from anon;
revoke execute on function public.enqueue_calendar_sync() from authenticated;
revoke execute on function public.fire_client_message_received_automations() from public;
revoke execute on function public.fire_client_message_received_automations() from anon;
revoke execute on function public.fire_client_message_received_automations() from authenticated;
revoke execute on function public.fire_date_reminder_automations() from public;
revoke execute on function public.fire_date_reminder_automations() from anon;
revoke execute on function public.fire_date_reminder_automations() from authenticated;
revoke execute on function public.fire_document_request_completed_automations() from public;
revoke execute on function public.fire_document_request_completed_automations() from anon;
revoke execute on function public.fire_document_request_completed_automations() from authenticated;
revoke execute on function public.fire_document_request_sent_automations() from public;
revoke execute on function public.fire_document_request_sent_automations() from anon;
revoke execute on function public.fire_document_request_sent_automations() from authenticated;
revoke execute on function public.fire_document_uploaded_automations() from public;
revoke execute on function public.fire_document_uploaded_automations() from anon;
revoke execute on function public.fire_document_uploaded_automations() from authenticated;
revoke execute on function public.fire_email_engagement_event_automations() from public;
revoke execute on function public.fire_email_engagement_event_automations() from anon;
revoke execute on function public.fire_email_engagement_event_automations() from authenticated;
revoke execute on function public.fire_engagement_letter_signed_automations() from public;
revoke execute on function public.fire_engagement_letter_signed_automations() from anon;
revoke execute on function public.fire_engagement_letter_signed_automations() from authenticated;
revoke execute on function public.fire_engagement_share_created_automations() from public;
revoke execute on function public.fire_engagement_share_created_automations() from anon;
revoke execute on function public.fire_engagement_share_created_automations() from authenticated;
revoke execute on function public.fire_firm_package_purchase_automations() from public;
revoke execute on function public.fire_firm_package_purchase_automations() from anon;
revoke execute on function public.fire_firm_package_purchase_automations() from authenticated;
revoke execute on function public.fire_invoice_overdue_automations() from public;
revoke execute on function public.fire_invoice_overdue_automations() from anon;
revoke execute on function public.fire_invoice_overdue_automations() from authenticated;
revoke execute on function public.fire_invoice_paid_automations() from public;
revoke execute on function public.fire_invoice_paid_automations() from anon;
revoke execute on function public.fire_invoice_paid_automations() from authenticated;
revoke execute on function public.fire_invoice_sent_automations() from public;
revoke execute on function public.fire_invoice_sent_automations() from anon;
revoke execute on function public.fire_invoice_sent_automations() from authenticated;
revoke execute on function public.fire_lead_assigned_automations() from public;
revoke execute on function public.fire_lead_assigned_automations() from anon;
revoke execute on function public.fire_lead_assigned_automations() from authenticated;
revoke execute on function public.fire_lead_created_automations() from public;
revoke execute on function public.fire_lead_created_automations() from anon;
revoke execute on function public.fire_lead_created_automations() from authenticated;
revoke execute on function public.fire_lead_status_changed_automations() from public;
revoke execute on function public.fire_lead_status_changed_automations() from anon;
revoke execute on function public.fire_lead_status_changed_automations() from authenticated;
revoke execute on function public.fire_lead_updated_automations() from public;
revoke execute on function public.fire_lead_updated_automations() from anon;
revoke execute on function public.fire_lead_updated_automations() from authenticated;
revoke execute on function public.fire_organizer_information_request_resolved_automations() from public;
revoke execute on function public.fire_organizer_information_request_resolved_automations() from anon;
revoke execute on function public.fire_organizer_information_request_resolved_automations() from authenticated;
revoke execute on function public.fire_organizer_response_review_decided_automations() from public;
revoke execute on function public.fire_organizer_response_review_decided_automations() from anon;
revoke execute on function public.fire_organizer_response_review_decided_automations() from authenticated;
revoke execute on function public.fire_partner_onboarding_created_automations() from public;
revoke execute on function public.fire_partner_onboarding_created_automations() from anon;
revoke execute on function public.fire_partner_onboarding_created_automations() from authenticated;
revoke execute on function public.fire_partner_onboarding_status_changed_automations() from public;
revoke execute on function public.fire_partner_onboarding_status_changed_automations() from anon;
revoke execute on function public.fire_partner_onboarding_status_changed_automations() from authenticated;
revoke execute on function public.fire_payment_plan_installment_paid_automations() from public;
revoke execute on function public.fire_payment_plan_installment_paid_automations() from anon;
revoke execute on function public.fire_payment_plan_installment_paid_automations() from authenticated;
revoke execute on function public.fire_pipeline_stage_entered_automations() from public;
revoke execute on function public.fire_pipeline_stage_entered_automations() from anon;
revoke execute on function public.fire_pipeline_stage_entered_automations() from authenticated;
revoke execute on function public.fire_quote_created_automations() from public;
revoke execute on function public.fire_quote_created_automations() from anon;
revoke execute on function public.fire_quote_created_automations() from authenticated;
revoke execute on function public.fire_quote_status_changed_automations() from public;
revoke execute on function public.fire_quote_status_changed_automations() from anon;
revoke execute on function public.fire_quote_status_changed_automations() from authenticated;
revoke execute on function public.fire_service_interest_automations() from public;
revoke execute on function public.fire_service_interest_automations() from anon;
revoke execute on function public.fire_service_interest_automations() from authenticated;
revoke execute on function public.fire_sms_engagement_event_automations() from public;
revoke execute on function public.fire_sms_engagement_event_automations() from anon;
revoke execute on function public.fire_sms_engagement_event_automations() from authenticated;
revoke execute on function public.fire_task_completed_automations() from public;
revoke execute on function public.fire_task_completed_automations() from anon;
revoke execute on function public.fire_task_completed_automations() from authenticated;
revoke execute on function public.fire_task_created_automations() from public;
revoke execute on function public.fire_task_created_automations() from anon;
revoke execute on function public.fire_task_created_automations() from authenticated;
revoke execute on function public.fire_task_overdue_automations() from public;
revoke execute on function public.fire_task_overdue_automations() from anon;
revoke execute on function public.fire_task_overdue_automations() from authenticated;
revoke execute on function public.flip_lead_on_quote_acceptance() from public;
revoke execute on function public.flip_lead_on_quote_acceptance() from anon;
revoke execute on function public.flip_lead_on_quote_acceptance() from authenticated;
revoke execute on function public.guard_delete_if_wired_to_automation() from public;
revoke execute on function public.guard_delete_if_wired_to_automation() from anon;
revoke execute on function public.guard_delete_if_wired_to_automation() from authenticated;
revoke execute on function public.is_ai_sandbox_workspace(p_workspace_id uuid) from public;
revoke execute on function public.is_ai_sandbox_workspace(p_workspace_id uuid) from anon;
revoke execute on function public.is_ai_sandbox_workspace(p_workspace_id uuid) from authenticated;
revoke execute on function public.is_module_unlocked(p_module_id uuid, p_user_id uuid) from public;
revoke execute on function public.is_module_unlocked(p_module_id uuid, p_user_id uuid) from anon;
revoke execute on function public.is_module_unlocked(p_module_id uuid, p_user_id uuid) from authenticated;
revoke execute on function public.is_platform_ai_operator() from public;
revoke execute on function public.is_platform_ai_operator() from anon;
revoke execute on function public.is_platform_ai_operator() from authenticated;
revoke execute on function public.learning_hub_reachable_workspaces(p_owner_workspace_id uuid) from public;
revoke execute on function public.learning_hub_reachable_workspaces(p_owner_workspace_id uuid) from anon;
revoke execute on function public.learning_hub_reachable_workspaces(p_owner_workspace_id uuid) from authenticated;
revoke execute on function public.network_child_relationship_types(p_workspace_id uuid) from public;
revoke execute on function public.network_child_relationship_types(p_workspace_id uuid) from anon;
revoke execute on function public.network_child_relationship_types(p_workspace_id uuid) from authenticated;
revoke execute on function public.notify_admins_of_automation_failure() from public;
revoke execute on function public.notify_admins_of_automation_failure() from anon;
revoke execute on function public.notify_admins_of_automation_failure() from authenticated;
revoke execute on function public.notify_appointment_booked_online() from public;
revoke execute on function public.notify_appointment_booked_online() from anon;
revoke execute on function public.notify_appointment_booked_online() from authenticated;
revoke execute on function public.notify_client_of_quote_change() from public;
revoke execute on function public.notify_client_of_quote_change() from anon;
revoke execute on function public.notify_client_of_quote_change() from authenticated;
revoke execute on function public.notify_invoice_paid() from public;
revoke execute on function public.notify_invoice_paid() from anon;
revoke execute on function public.notify_invoice_paid() from authenticated;
revoke execute on function public.notify_organizer_information_request(p_request_id uuid, p_message text) from public;
revoke execute on function public.notify_organizer_information_request(p_request_id uuid, p_message text) from anon;
revoke execute on function public.notify_organizer_information_request(p_request_id uuid, p_message text) from authenticated;
revoke execute on function public.notify_organizer_reviewed() from public;
revoke execute on function public.notify_organizer_reviewed() from anon;
revoke execute on function public.notify_organizer_reviewed() from authenticated;
revoke execute on function public.notify_payment_received() from public;
revoke execute on function public.notify_payment_received() from anon;
revoke execute on function public.notify_payment_received() from authenticated;
revoke execute on function public.notify_staff_document_request_completed() from public;
revoke execute on function public.notify_staff_document_request_completed() from anon;
revoke execute on function public.notify_staff_document_request_completed() from authenticated;
revoke execute on function public.portal_client_id() from public;
revoke execute on function public.portal_client_id() from anon;
revoke execute on function public.portal_client_id() from authenticated;
revoke execute on function public.record_agent_evidence(p_run_id uuid, p_evidence_type text, p_payload jsonb, p_finding_id uuid, p_storage_path text) from public;
revoke execute on function public.record_agent_evidence(p_run_id uuid, p_evidence_type text, p_payload jsonb, p_finding_id uuid, p_storage_path text) from anon;
revoke execute on function public.record_agent_evidence(p_run_id uuid, p_evidence_type text, p_payload jsonb, p_finding_id uuid, p_storage_path text) from authenticated;
revoke execute on function public.resolve_organizer_information_request(p_request_id uuid) from public;
revoke execute on function public.resolve_organizer_information_request(p_request_id uuid) from anon;
revoke execute on function public.resolve_organizer_information_request(p_request_id uuid) from authenticated;
revoke execute on function public.resolve_organizer_information_request_if_done() from public;
revoke execute on function public.resolve_organizer_information_request_if_done() from anon;
revoke execute on function public.resolve_organizer_information_request_if_done() from authenticated;
revoke execute on function public.revoke_expired_portal_access() from public;
revoke execute on function public.revoke_expired_portal_access() from anon;
revoke execute on function public.revoke_expired_portal_access() from authenticated;
revoke execute on function public.set_organizer_answer_review_status(p_answer_id uuid, p_status review_status, p_note text) from public;
revoke execute on function public.set_organizer_answer_review_status(p_answer_id uuid, p_status review_status, p_note text) from anon;
revoke execute on function public.set_organizer_answer_review_status(p_answer_id uuid, p_status review_status, p_note text) from authenticated;
revoke execute on function public.set_partner_onboarding_document_request(p_workspace_id uuid, p_onboarding_id uuid, p_document_request_id uuid) from public;
revoke execute on function public.set_partner_onboarding_document_request(p_workspace_id uuid, p_onboarding_id uuid, p_document_request_id uuid) from anon;
revoke execute on function public.set_partner_onboarding_document_request(p_workspace_id uuid, p_onboarding_id uuid, p_document_request_id uuid) from authenticated;
revoke execute on function public.should_advance_wait_until_step(p_pending_id uuid) from public;
revoke execute on function public.should_advance_wait_until_step(p_pending_id uuid) from anon;
revoke execute on function public.should_advance_wait_until_step(p_pending_id uuid) from authenticated;
revoke execute on function public.sync_client_emails_forward() from public;
revoke execute on function public.sync_client_emails_forward() from anon;
revoke execute on function public.sync_client_emails_forward() from authenticated;
revoke execute on function public.sync_client_phones_forward() from public;
revoke execute on function public.sync_client_phones_forward() from anon;
revoke execute on function public.sync_client_phones_forward() from authenticated;
revoke execute on function public.sync_client_primary_email() from public;
revoke execute on function public.sync_client_primary_email() from anon;
revoke execute on function public.sync_client_primary_email() from authenticated;
revoke execute on function public.sync_client_primary_phone() from public;
revoke execute on function public.sync_client_primary_phone() from anon;
revoke execute on function public.sync_client_primary_phone() from authenticated;
revoke execute on function public.sync_client_relationships_from_answer_change() from public;
revoke execute on function public.sync_client_relationships_from_answer_change() from anon;
revoke execute on function public.sync_client_relationships_from_answer_change() from authenticated;
revoke execute on function public.sync_client_relationships_from_organizer_submission() from public;
revoke execute on function public.sync_client_relationships_from_organizer_submission() from anon;
revoke execute on function public.sync_client_relationships_from_organizer_submission() from authenticated;
revoke execute on function public.tag_client_on_invoice_paid() from public;
revoke execute on function public.tag_client_on_invoice_paid() from anon;
revoke execute on function public.tag_client_on_invoice_paid() from authenticated;
revoke execute on function public.tag_client_on_invoice_sent() from public;
revoke execute on function public.tag_client_on_invoice_sent() from anon;
revoke execute on function public.tag_client_on_invoice_sent() from authenticated;
revoke execute on function public.update_partner_onboarding_requirements(p_workspace_id uuid, p_onboarding_id uuid, p_agreement_required boolean, p_documents_required boolean, p_training_required boolean, p_bank_software_setup_required boolean) from public;
revoke execute on function public.update_partner_onboarding_requirements(p_workspace_id uuid, p_onboarding_id uuid, p_agreement_required boolean, p_documents_required boolean, p_training_required boolean, p_bank_software_setup_required boolean) from anon;
revoke execute on function public.update_partner_onboarding_requirements(p_workspace_id uuid, p_onboarding_id uuid, p_agreement_required boolean, p_documents_required boolean, p_training_required boolean, p_bank_software_setup_required boolean) from authenticated;
revoke execute on function public.withdraw_partner_onboarding(p_workspace_id uuid, p_onboarding_id uuid, p_reason text) from public;
revoke execute on function public.withdraw_partner_onboarding(p_workspace_id uuid, p_onboarding_id uuid, p_reason text) from anon;
revoke execute on function public.withdraw_partner_onboarding(p_workspace_id uuid, p_onboarding_id uuid, p_reason text) from authenticated;

revoke all privileges on table public.rate_limit_hits from anon, authenticated;
revoke all privileges on table public.workspace_ghl_connections from anon, authenticated;
revoke all privileges on table public.workspace_jotform_connections from anon, authenticated;
revoke all privileges on table public.workspace_partner_purchase_webhooks from anon, authenticated;
---